apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
spec:
  project: default
  sources:
    # Values repository
    - repoURL: https://github.com/pkeshi-s-castle/radagast-gitops.git
      targetRevision: main
      ref: values

    # Tailscale Operator Helm Chart
    - repoURL: https://pkgs.tailscale.com/helmcharts
      chart: tailscale-operator
      targetRevision: "1.*"
      helm:
        releaseName: tailscale-operator
        valueFiles:
          - $values/apps/workloads/tailscale-operator/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
